/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.QuickSort;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  @Teast 
  public void quickSortTest() {
        ArrayList<Integer> arrayList = new ArrayList<>();
        arrayList.add(8);
        arrayList.add(5);
        arrayList.add(27);
        arrayList.add(1);
        arrayList.add(17);
        arrayList.add(15);
        QuickSort(arrayList , 0 , arrayList.size()-1);
        ArrayList<Integer> arr2 = new ArrayList<>();
        arr2.add(1);
        arr2.add(5);
        arr2.add(8);
        arr2.add(15);
        arr2.add(17);
        arr2.add(27);
      
        assertEquals(arrayList , arr2);
}
