/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue.pseudo;


import stack.queue.pseudo.stackqueuepseudoPackage.pseudoQueue;



public class App {


    public static void main(String[] args) {
        pseudoQueue<Integer> satckIn = new pseudoQueue<>();
        satckIn.enqueue(20);
        satckIn.enqueue(15);
        satckIn.enqueue(10);
        System.out.println("\nList: ");
        System.out.println(satckIn);
        satckIn.enqueue(5);
        System.out.println("\nEnqueue:  ");
        System.out.println(satckIn);


        satckIn.dequeue();
        System.out.println("\n Dequeue : ");
        System.out.println(satckIn);

        satckIn.dequeue();
        System.out.println("Dequeue : \n");
        System.out.println(satckIn);

    }
}