/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bracketsStackQueue;

public class App {

    public static void main(String[] args) {
        String validate1 = "()[[Extra Characters]]";
        String validate2 = "{}{Code}[Fellows](())";
        String validate3 = "(](";
        String validate4 = "{(})";
        Brackets brackets1= new Brackets(validate1);
        Brackets brackets2= new Brackets(validate2);
        Brackets brackets3= new Brackets(validate3);
        Brackets brackets4= new Brackets(validate4);

        System.out.println("_____________________________________________________________________");
        System.out.println("******************** Bracket 1 ***********************************");
        System.out.println(brackets1.validateBrackets());
        System.out.println("******************** Bracket 2 ***********************************");
        System.out.println(brackets2.validateBrackets());
        System.out.println("******************** Bracket 3***********************************");
        System.out.println(brackets3.validateBrackets());
        System.out.println("******************** Bracket 4 ***********************************");
        System.out.println(brackets4.validateBrackets());
        System.out.println("_____________________________________________________________________");

    }

}
