/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package data.structures.and.algorithms;

public class App {
       public static void main(String[] args) {
       int arraySorted[]={1,2,5,8,9,14,15,63,85,155,158};
       System.out.println(BinarySearch(arraySorted, 155));
    }


    public static int BinarySearch(int sortedArr[],int valueSearch){
           int firstEle = 0;
           int lastEle = sortedArr.length-1;
           int mid = (first+last)/2;
           while(first<=last ){
             if (sortedArr[mid]<valueSearch)
             {
                 first = mid+1;
             }
             else if (sortedArr[mid]==valueSearch)
             {
                 return sortedArr[mid];
               breake;
             }
             else
             {
                 last = mid -1;
                 mid =(first + last )/2;
             }
             if (first>last)
              return -1;
        }


    }
}
