/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InsertionSort;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    public void isertionsortTest (){
        int[] test = {8,4,23,42,16,15};
        int[] resultForTest = App.insertionSort(test);
        int[] test2 = {4,8,15,16,23,42};

        assertArrayEquals(test ,test2);
}

}
