/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.hashtable;

public class App {

    public static void main(String[] args) {

        System.out.println("Challenge 30 Done !!! ");

    }
}
