/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.QuickSort;


public class App {

    public static void main(String[] args) {

    }

    public void quickSort(int arr[], int left, int right) {
        if (left < right) {
            int partitionIndex = partition(arr, left, right);

            quickSort(arr, left, partitionIndex-1);

            quickSort(arr, partitionIndex+1, right);
        }
    }
    private int partition(int arr[], int left, int right) {
        int pivot = arr[right];
        int low = (left-1);

        for (int index = left; index < right; index++) {

            if (arr[index] <= pivot) {
                low++;
                swap(arr, index, low);
            }
        }

        swap(arr, right, low+1);

        return low + 1;
    }


    public static void swap(int[] arr ,int i, int low){

        int temp = arr[i];
        arr[i] = arr[low];
        arr[low] = temp;
    }
}
