/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.QuickSort;

import java.util.ArrayList;

public class App {

    public static void main(String[] args) {

    }

    public static void quickSort(ArrayList<Integer> arr , int left , int right){
        if(left < right){
            int position =  partition(arr, left, right) ;
            quickSort(arr, left, position - 1);
            quickSort(arr, position + 1, right);
        }

    }

    public static int partition(ArrayList<Integer> arr , int left , int right){
        int pivot = arr.get(right);
        int low = left - 1 ;
        for (int i = left ; i < right ; i++){
            if (arr.get(i) <= pivot){
                low++;
                swap(arr, i, low)  ;
            }

        }
        swap(arr, right, low + 1);
        return low + 1 ;
    }

    public static void swap(ArrayList<Integer> arr, int i, int low){
        int temp = arr.get(i);
        arr.set(i , arr.get(low));
        arr.set(low , temp);
    }
}
