/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InsertionSort;

public class App {
    public static int[] insertionSort(int[] arr){
        int j , temp ;

        for (int index = 1 ; index<= arr.length ;index++ ){
            j = index-1;
            temp = arr[index];

            while (j >= 0 && temp < arr[j]){
                arr[j + 1] = arr[j];
                j--;

            }
            arr[j + 1] = temp;
        }
        return arr;
    }


    public static void main(String[] args) {

        try {
            int[] test = {8,4,23,42,16,15};
            int[] solutionForTest = insertionSort(test);

            for(int idx = 0 ; idx < solutionForTest.length ; idx++ ){
                   System.out.println(solutionForTest[idx]);
               }
            } catch (Exception e) {
            System.out.println("Error ");
            }
    }


}
