/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph.depth.first;

import graph.depth.first.graoh.Graph;
import graph.depth.first.graoh.Vertix;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Graph graph = new Graph();

        graph.addVerNode("A");
        graph.addVerNode("B");
        graph.addVerNode("C");
        graph.addVerNode("D");
        graph.addVerNode("E");
        graph.addVerNode("F");
//        graph.addVerNode("J");
//        graph.addVerNode("H");

        graph.addEdge("A","B");
        graph.addEdge("A","D");

        graph.addEdge("B","D");
        graph.addEdge("B","C");


        graph.addEdge("D","F");
//        graph.addEdge("D","H");
        graph.addEdge("D","E");
        graph.addEdge("D","B");

//        graph.addEdge("C","G");

        graph.addEdge("F","H");

        String result = graph.depthFirst(new Vertix("A")).toString();


    }
}
