/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leftJoin;

import leftJoin.Hash.HashTable;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
      String str = "It was the best of times, it was the worst of times," +
              " it was the age of wisdom, it was the age of foolishness," +
              " it was the epoch of belief, it was the epoch of incredulity," +
              " it was the season of Light, it was the season of Darkness," +
              " it was the spring of hope, it was the winter of despair," +
              " we had everything before us, we had nothing before us," +
              " we were all going direct to Heaven, " +
              "we were all going direct the other way – in short," +
              " the period was so far like the present period," +
              " that some of its noisiest authorities insisted on its being received," +
              " for good or for evil, in the superlative degree of comparison only...";

        HashTable <String,String>hashTable= new HashTable<>() ;

       String string=  hashTable.repeatedWord(str);
        assertEquals(string, "it");
    }

    @Test void appHas(){
        LeftJoin leftJoinObj = new LeftJoin();
        HashTable<String, String> stringHashTable = new HashTable<String,String>();
        stringHashTable.set("diligent", "employed");
        stringHashTable.set("fond", "enamored");
        stringHashTable.set("guide", "usher");
        stringHashTable.set("outfit", "garb");
        stringHashTable.set("wrath", "anger");

        HashTable<String, String> stringHashTable1 = new HashTable<String,String>();
        stringHashTable1.set("diligent", "idle");
        stringHashTable1.set("fond", "averse");
        stringHashTable1.set("guide", "follow");
        stringHashTable1.set("flow", "jam");
        stringHashTable1.set("wrath", "delight");

        //////////////////////////////////////////////////////////////////////////

        String str = leftJoinObj.leftJoin(stringHashTable,stringHashTable1).toString();
        System.out.println(str);

        String string = "[ { diligent , employed , idle }  ,  { wrath , anger , delight }  ,  { fond , enamored , averse }  ,  { guide , usher , follow }  ,  { outfit , garb , null }  ]";

        assertEquals(str,string);
    }
}
