/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.hashtable;


import org.junit.jupiter.api.Test;

import java.util.HashMap;

import static com.hashtable.App.repeatedWord;
import static org.junit.jupiter.api.Assertions.assertEquals;


//Setting a key/value to your hashtable results in the value being in the data structure
//Retrieving based on a key returns the value stored
//Successfully returns null for a key that does not exist in the hashtable
//Successfully returns a list of all unique keys that exist in the hashtable
//Successfully handle a collision within the hashtable
//Successfully retrieve a value from a bucket within the hashtable that has a collision
//Successfully hash a key to an in-range value
class AppTest {



//        @Test
//    public void settingTest() {
//
//        HashMap<String, String> hashMap = new HashMap<>();
//        hashMap.set("Hadeel", "Mama");
//        hashMap.set("Maria", "Baby");
//        hashMap.set("Jood", "Sister");
//
//        int actual = 3;
//        int expected = hashMap.getSize();
//
//        assertEquals(expected,actual);
//
//    }

//"Once upon a time, there was a brave princess who..."
    //"a"
//"It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only...
    //"it"
//"It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York..."
    //"summer"
@Test
    public void repeatedWTest (){

//            HashTable<String , String> repeatedWordTest = new HashTable<>();
         System.out.println("------------=REPEATED WORD=---------");
        String resul = (repeatedWord("Once upon a time, there was a brave princess who..."));
        assertEquals(resul , "a");
}
}
