/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package breadth.first.traversal;

import breadth.first.traversal.graoh.Graph;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Graph graph = new Graph();

        graph.addVerNode("Pandora");
        graph.addVerNode("Arendelle");
        graph.addVerNode("Narnia");
        graph.addVerNode("Naboo");
        graph.addVerNode("Metroville");
        graph.addVerNode("Monstroplolis");

        graph.addEdge("Pandora","Arendelle");
        graph.addEdge("Arendelle","Metroville");
        graph.addEdge("Arendelle","Monstroplolis");
        graph.addEdge("Metroville","Narnia");
        graph.addEdge("Metroville","Naboo");
        graph.addEdge("Metroville","Monstroplolis");
        graph.addEdge("Monstroplolis","Naboo");
        graph.addEdge("Naboo","Narnia");


       String result = graph.breadthFirst("Pandora").toString();
        assertEquals(
                result,
                "[Pandora, Arendelle, Metroville, Monstroplolis, Narnia, Naboo]"
        );
    }
}
