/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leftJoin;

import leftJoin.Hash.HashTable;

public class App {

    public static void main(String[] args) {
        LeftJoin leftJoinObj = new LeftJoin();
        HashTable<String, String> stringHashTable = new HashTable<String,String>();
        stringHashTable.set("diligent", "employed");
        stringHashTable.set("fond", "enamored");
        stringHashTable.set("guide", "usher");
        stringHashTable.set("outfit", "garb");
        stringHashTable.set("wrath", "anger");

        HashTable<String, String> stringHashTable1 = new HashTable<String,String>();
        stringHashTable1.set("diligent", "idle");
        stringHashTable1.set("fond", "averse");
        stringHashTable1.set("guide", "follow");
        stringHashTable1.set("flow", "jam");
        stringHashTable1.set("wrath", "delight");

        //////////////////////////////////////////////////////////////////////////
        System.out.println("output : ");
        System.out.println(leftJoinObj.leftJoin(stringHashTable,stringHashTable1));

    }
}
