/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.graph;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    public void sizeTest(){
        Graph graph=new Graph();
        graph.addNode("node1");
        graph.addNode("node2");
        graph.addNode("node3");

        assertEquals(3,graph.size());
    }



}
