/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge01;

public class App {


    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }



    public static void reverse(int array[]){
        int  newArray = new int [array.length];
        int last = array.length ;
        for (int i=0;i<array.length;i++;last =last-1){

            newArray=[last-1]=array[i];
        }
        for (int i=0;i<array.length;i++){
            System.out.println (newArray[i]+" ");
        }
    }
}
