/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue.pseudo;

import org.junit.jupiter.api.Test;
import stack.queue.pseudo.stackqueuepseudoPackage.pseudoQueue;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    pseudoQueue<Integer> test =new pseudoQueue<>();
@Test
    void testEnqueue(){

    test.enqueue(10);
    test.enqueue(11);
    test.enqueue(12);
    test.enqueue(13);

    assertEquals("[13] -> [12] -> [11] -> [10] -> ", test.toString());
}
@Test
    void testDequeue(){
    test.enqueue(10);
    test.enqueue(11);
    test.enqueue(12);
    test.enqueue(13);
    test.dequeue();
    assertEquals("[13] -> [12] -> [11] -> ", test.toString());
}
}
