/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.MergeSort;

public class App {


    public static void main(String[] args) {



        int[] arr = {8,4,23,42,16,15};
        System.out.println(mergeSort(arr).toString());
        printArr(arr);
    }


    public static int[] mergeSort(int[] arr){
        int n = arr.length;
//        if n > 1
//      DECLARE mid <-- n/2
//      DECLARE left <-- arr[0...mid]
//      DECLARE right <-- arr[mid...n]

        int mid = n / 2 ;
        int[] right = new int[mid];
        int[] left = new int[n - mid];

        if (n > 1) {

            for (int index = 0; index < mid; index++)
                left[index] = arr[index];

            for (int index = mid; index < n; index++) {
                right[index - mid] = arr[index];
            }

            mergeSort(left);
            mergeSort(right);
            merge(left, right, arr);
        }

        return arr;
    }
    public static void merge (int[] left ,int[] right ,int[] arr ){

        int i=0,j=0,k=0;

        if (left[i] <= right[j]) {
            arr[k] = left[i];
            i = i + 1;
        } else {
            arr[k] = right[j];
            j = j + 1;
        }

        k = k + 1;

        while (i < left.length) {
            arr[k++] = left[i++];
        }

        while (j < right.length) {
            arr[k++] = right[j++];
        }
    }

    public static void printArr (int[] arr){

        for(int index = 0 ; index < arr.length ; index ++){
            System.out.println("["+arr[index]+"] ");
        }
    }

}


