/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class App {

    public static void main(String[] args) {
        LinkedList <Integer> List = new LinkedList<Integer>();
        //insert
        List.insert(8);
        List.insert(5);
        //incloudes
        System.out.println("The include bool" + List.includes( 8));
        System.out.println("The include bool" + List.includes(15));
        //ToString
        System.out.println("To String  "+List.toString());


    }
}
