/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AnimalShelter;

import classes.Animal;
import classes.AnimalShelter;

public class App {


    public static void main(String[] args){
    AnimalShelter myAnimal=new AnimalShelter();
    myAnimal.enQueue(new Animal("dog"));
    myAnimal.enQueue(new Animal("cat"));
    myAnimal.enQueue(new Animal("dog"));
    myAnimal.enQueue(new Animal("cat"));
    myAnimal.enQueue(new Animal("dog"));
    myAnimal.enQueue(new Animal("cat"));
    myAnimal.enQueue(new Animal("cat"));
    myAnimal.enQueue(new Animal("dog"));
    myAnimal.enQueue(new Animal("dog"));


        System.out.println(myAnimal.deQueue("dog"));
        System.out.println(myAnimal.deQueue("cat"));

        System.out.println(myAnimal);

    }
}
